### PR TITLE
Slider Fix. fix #159

### LINKED ISSUE #159: Use drop-down menus instead of TextFields for changing the settings.

### PR DESCRIPTION
**Pull request by mxkso**

### CODE REVIEW

File: src/components/views/Settings.js [hunk 1]
```diff
@@ -2,27 +2,51 @@ import {api} from 'helpers/api';
...
-        setRounds(event.target.value)
-    }
-    const handleTimeChange = (event) => {
-        setTime(event.target.value)
+
+    useEffect(() => {
+        const newValue = sliderRoundsValueRef.current;
+        if (!isNaN(newValue)) {
+          setRounds(newValue);
+          doSave();
```
Comment (felixmerz00) [inline src/components/views/Settings.js:24]: As far as I know the setRounds doesn't instantly update the rounds value. Wouldn't it be smarter to not call doSave(). Instead of doSave have a useEffect function which depends on the variable rounds, roundTime and topic.

Comment (mxkso) [reply src/components/views/Settings.js:23]: I changed it to only doSave().
